version: '3'

services:
  shared_mysql:
    container_name: repo-mysql
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]